import type { HomePage } from './types'

export const home: HomePage = {
  hero: {
    eyebrow: 'Compassion in action',
    title: 'Small acts of <mark>kindness,</mark> gathered into <em>extraordinary</em> change.',
    captions: ['Empowering through learning', 'Meal support initiatives', 'Nurturing Growth'],
    slides: [
      {
        image: '/images/hero-slide-1.webp',
        h1Line1: 'Nurturing lives.',
        h1Line2: 'Nourishing communities.',
        lede: 'We believe lasting change begins with compassion in action. Through everyday acts of giving and support, we work toward a world where wellbeing, dignity, and opportunity reach everyone.',
        btnText: 'Get involved',
        btnUrl: '/get-involved',
        btn2Text: 'Support our work',
        btn2Url: '/donate#donate-form',
      },
      {
        image: '/images/hero-slide-2.webp',
        h1Line1: 'Rooted in compassion.',
        h1Line2: 'Guided by service.',
        lede: 'A quiet commitment to doing good, every day. Through consistent, heartfelt acts that touch lives where it matters most.',
        btnText: 'Read our story',
        btnUrl: '/about',
      },
      {
        image: '/images/planet-slide-3.webp',
        h1Line1: 'Small acts.',
        h1Line2: 'Extraordinary change.',
        lede: 'Nourishment, peace of mind, learning and care for our planet: the four causes we champion, and the initiatives that bring them to life.',
        btnText: 'See what we do',
        btnUrl: '/what-we-do',
      },
    ],
  },
  pills: [
    'Food distribution',
    'Inner wellbeing',
    'Learning & growth',
    'Environmental care',
  ],
  marquee: [
    'Meals shared',
    'Minds eased',
    'Doors opened',
    'Earth tended',
  ],
  gallery: {
    eyebrow: 'Field notes',
    heading: 'Days in the communities we walk with',
    deck: 'Every frame is a real day of work. New photographs are added after each drive.',
    tiles: [
      {
        image: '/images/story-1-warm-meal.webp',
        category: 'Nourishment',
        caption: 'A midday meal, shared',
        span: 'big',
        slides: [
          { image: '/images/story-1-warm-meal.webp', caption: 'A midday meal, shared' },
          { image: '/images/nourishment-slide-2.webp', caption: 'Food for every child' },
          { image: '/images/wwd-nourishment.webp', caption: 'Reaching the last mile' },
        ],
      },
      {
        image: '/images/story-3-quiet-life.webp',
        category: 'Peace of mind',
        caption: 'A quiet morning',
        slides: [
          { image: '/images/story-3-quiet-life.webp', caption: 'A quiet morning' },
          { image: '/images/pillar-2-peace.webp', caption: 'Finding stillness together' },
          { image: '/images/wwd-peace.webp', caption: 'Spaces for inner renewal' },
        ],
      },
      {
        image: '/images/home-our-story.webp',
        category: 'Community',
        caption: 'Listening first',
        slides: [
          { image: '/images/home-our-story.webp', caption: 'Listening first' },
          { image: '/images/community-slide-2.webp', caption: 'Building trust, together' },
          { image: '/images/about-hero.webp', caption: 'Rooted in community' },
        ],
      },
      {
        image: '/images/story-2-community-teach.webp',
        category: 'Learning',
        caption: 'A class in the open',
        span: 'tall',
        slides: [
          { image: '/images/story-2-community-teach.webp', caption: 'A class in the open' },
          { image: '/images/learning-slide-2.webp', caption: 'Knowledge as a right' },
          { image: '/images/learning-slide-3.webp', caption: 'Every child, every lesson' },
        ],
      },
      {
        image: '/images/home-our-work.webp',
        category: 'Volunteers',
        caption: 'Hands in the soil',
        span: 'tall',
        slides: [
          { image: '/images/home-our-work.webp', caption: 'Hands in the soil' },
          { image: '/images/volunteers-slide-2.webp', caption: 'Showing up, every drive' },
          { image: '/images/gi-hero.webp', caption: 'A movement of quiet service' },
        ],
      },
      {
        image: '/images/planet-slide-1.webp',
        category: 'Our planet',
        caption: 'Planting day',
        span: 'wide',
        slides: [
          { image: '/images/planet-slide-1.webp', caption: 'Planting day' },
          { image: '/images/planet-slide-2.webp', caption: 'Care for the earth we share' },
          { image: '/images/planet-slide-3.webp', caption: 'Growing something green' },
        ],
      },
    ],
  },
  mission: {
    eyebrow: 'Our purpose',
    statementMarked: 'A quiet <mark>commitment</mark> to doing good, every <mark>day</mark>.',
    body: 'Vagh Foundation is dedicated to uplifting communities through initiatives that touch lives where it matters most: nourishment for the body, peace for the mind, knowledge for the future, and care for the world we share. Guided by service and humility, we strive to make kindness a way of life.',
    btnText: 'Our story',
    btnUrl: '/about',
  },
  hCards: {
    work: {
      image: '/images/home-our-work.webp',
      desc: 'The four causes we champion (nourishment, peace of mind, learning and care for our planet) and the initiatives that bring them to life.',
      href: '/what-we-do',
    },
    story: {
      image: '/images/home-our-story.webp',
      desc: 'Vagh Foundation was born from a simple belief: that meaningful change is built through consistent, heartfelt acts of service.',
      href: '/about',
    },
  },
  founder: {
    eyebrow: 'A message from our founder',
    photo: '/images/founder-dhirubhai.webp',
    name: 'Dhirubhai S. Vagh',
    role: 'Founder, Vagh Foundation',
    quote: 'Compassion, when practiced with consistency, becomes a quiet force. It doesn’t demand attention. It simply shows up, day after day, wherever it is needed most. Vagh Foundation was born from this belief, and grows with every act of service.',
  },
  pillars: {
    eyebrow: 'Plate I–IV',
    headingMarked: 'Four <mark>pillars</mark>, one shared belief',
    sub: 'That wellbeing is holistic, and that everyone deserves the chance to thrive.',
    items: [
      {
        title: 'Nourishment for all',
        body: 'Food distribution initiatives that ensure no one is left behind when it comes to a basic human need.',
        image: '/images/pillar-1-nourishment.webp',
      },
      {
        title: 'Peace of mind',
        body: 'Support for spaces of inner wellbeing and self-reflection, helping people find calm and renewal.',
        image: '/images/pillar-2-peace.webp',
      },
      {
        title: 'Empowering through learning',
        body: 'Access to knowledge and skill-building that opens doors of opportunity for curious minds.',
        image: '/images/pillar-3-learning.webp',
      },
      {
        title: 'Caring for our planet',
        body: 'Sustainability initiatives that protect the environment for generations to come.',
        image: '/images/pillar-4-planet.webp',
      },
    ],
    btnText: 'Explore what we do',
    btnHref: '/what-we-do',
  },
  ideas: {
    eyebrow: 'Ideas & stories',
    heading: 'Voices from our work',
    sub: 'Reflections, moments and voices from the communities we walk alongside.',
    items: [
      {
        kicker: 'Nourishment',
        topic: 'nourishment',
        title: 'What does a warm meal really give?',
        body: 'Beyond hunger: dignity, and evenings a family can share.',
        image: '/images/story-1-warm-meal.webp',
      },
      {
        kicker: 'Learning',
        topic: 'learning',
        title: 'Can a community teach itself?',
        body: 'Neighbours becoming teachers in the learning circles.',
        image: '/images/story-2-community-teach.webp',
      },
      {
        kicker: 'Wellbeing',
        topic: 'wellbeing',
        title: 'How much quiet does a life need?',
        body: 'On the spaces we support for reflection and peace.',
        image: '/images/story-3-quiet-life.webp',
      },
    ],
  },
  statement: 'Every meal shared, every mind at peace, every life empowered. <mark>It all begins with people who care.</mark>',
  gateFeature: {
    image: '/images/home-compassion-in-action.webp',
    kicker: 'Compassion in action',
    titleMarked: 'Small acts, gathered together, become a <mark>force</mark> for extraordinary change.',
    desc: 'We walk quietly alongside those we serve, offering nourishment, supporting peace of mind, encouraging learning, and caring for the world we all share.',
    btnText: 'Explore what we do',
    btnUrl: '/what-we-do',
  },
  cta: {
    headingMarked: 'Together, we can do <em>more</em>',
    body: 'Change is a collective effort. There’s a place for everyone in ours.',
    btn1Text: 'Volunteer with us',
    btn1Href: '/volunteer',
    btn2Text: 'Make a donation',
    btn2Href: '/donate#donate-form',
  },
}